### PR TITLE
Fix ANSI colors for zsh &  Add execute permission to file ssl

### PR DESCRIPTION
**Pull request by muyinliu**

### CODE REVIEW

**Comment by muyinliu** [comment]
Thanks for providing such awesome tool.

**Review by bobbyiliev — CHANGES_REQUESTED** [review]
That looks good! Thanks for the suggestion!

I think that it's better to add an if statement to check if the shell is zsh otherwise the colors would not work on some other shells.

What do you think?

**Comment by muyinliu** [comment]
The fix is compatible with `bash` too(tested with **bash v3.2.57**、**bash v5.0.18** on macOS).

**Review by bobbyiliev — APPROVED** [review]

**Comment by bobbyiliev** [comment]
Looks good indeed! Thanks for the PR!

**Pull request merged**
